on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  balena_cloud_build:
    strategy:
      matrix:
        fleet:
          - "techops_balena1/octo-browser-aarch64"
          - "techops_balena1/octo-browser-amd64"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: balena-io/deploy-to-balena-action@v2.0.131
        id: build
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ matrix.fleet }}
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
